### ISSUE TITLE
Mark package version as v5 to match pgx one

### ISSUE THREAD

**Issue by vgarvardt** [jackc/pgx-gofrs-uuid#1]
Not really an issue but an idea - make go package `v5` and tag it as `v5.x` to match supported major `pgx` version.

**Comment by jackc** [comment]
I think this decision would better made when and if there is a pgx `v6`. If a `v6` had a different PG type interface then this package having `v5` and `v6` matching versions could make sense. But if a `v6` kept the same PG type interface then a `v5` version would actually be counterproductive.
