### ISSUE TITLE
is there a reason gofrs/uuid is chosen over google/uuid?

### ISSUE THREAD

**Issue by mrkagelui** [jackc/pgx-gofrs-uuid#2]
as titled, legacy? an arbitrary choice? or is there any feature/performance benefit?

**Comment by jackc** [comment]
No reason that I can remember. It's been quite a while (originally pgx used its predecessor https://github.com/satori/go.uuid).

**Comment by mrkagelui** [comment]
> No reason that I can remember. It's been quite a while (originally pgx used its predecessor https://github.com/satori/go.uuid).

thank you Jack!
